version: "3.8"

networks: 
  venttys-net:
    name: venttys-net

volumes:
  venttys-zookeeper:
    name: venttys-zookeeper
  venttys-kafka:
    name: venttys-kafka
  venttys-mongo:
    name: venttys-mongo
  venttys-wh-tokens:
    name: venttys-wh-tokens
  venttys-wh-public:
    name: venttys-wh-public

services:

  mongo:
    image: mongo
    container_name: venttys-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: venttys
      MONGO_INITDB_ROOT_PASSWORD: dmVudHR5cw
    volumes: 
      - venttys-mongo:/data/db
    networks:
      - venttys-net

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    container_name: venttys-zookeeper
    restart: always
    volumes:
      - "venttys-zookeeper:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - venttys-net

  kafka:
    image: docker.io/bitnami/kafka:2
    container_name: venttys-kafka
    restart: always
    volumes:
      - venttys-kafka:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=venttys-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://venttys-kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - venttys-net
